/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ExpenseLazyImport = createFileRoute('/expense')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ExpenseLazyRoute = ExpenseLazyImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/expense.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/expense': typeof ExpenseLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/expense': typeof ExpenseLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/expense': typeof ExpenseLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/expense'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/expense'
  id: '__root__' | '/' | '/expense'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ExpenseLazyRoute: typeof ExpenseLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ExpenseLazyRoute: ExpenseLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/expense"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/expense": {
      "filePath": "expense.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
